#!/bin/bash
#

if [[ "${1}" == "go" ]]; then
	ECHO=
	shift
else
	ECHO=echo
fi

DEST="${1}"
if [[ -z "${DEST}" ]]; then
	echo "*** please supply the home-assistant /config directory"
	exit 1
fi	
if [[ ! -d "${DEST}" ]]; then
	echo "*** please make sure the destination directory exists"
	exit 1
fi

if [[ -n "${ECHO}" ]]; then
	echo "**** would run the following commands, use './install go $1' to do the work"
fi

${ECHO} mkdir -p "${DEST}/custom_components"
if [[ -n $(command -v fd) ]]; then
	fd -e py . custom_components --exec ${ECHO} cp -vf --parents {} "${DEST}" ;
else
	${ECHO} cp -afv custom_components/aarlo "${DEST}/custom_components"
fi

