# Describes the format for available virtual services

turn_on:
  name: Turn On
  description: Turn on a binary sensor.
  target:
    entity:
      integration: virtual
      domain: binary_sensor

turn_off:
  name: Turn Off
  description: Turn off a binary sensor.
  target:
    entity:
      integration: virtual
      domain: binary_sensor

toggle:
  name: Toggle
  description: Toggle a binary sensor.
  target:
    entity:
      integration: virtual
      domain: binary_sensor

set:
  name: Set
  description: Set the value of a sensor.
  target:
    entity:
      integration: virtual
      domain: sensor
  fields:
    value:
      name: Value
      description: Value to set state to.
      required: true
      example: '10'
      selector:
        text:

set_available:
  name: Set Availability
  description: Set availability of an entity.
  target:
    entity:
      integration: virtual
  fields:
    value:
      name: Value
      description: Is the entity available.
      example: false
      required: true
      selector:
        boolean:

set_climate_temperature:
  name: Set Climate Temperature
  description: Set the target temperature of a climate device.
  target:
    entity:
      integration: virtual
      domain: climate
  fields:
    temperature:
      name: Temperature
      description: Target temperature to set.
      example: 22.0
      required: true
      selector:
        number:
          min: -50
          max: 100
          step: 0.5
          unit_of_measurement: "°C"

set_climate_hvac_mode:
  name: Set Climate HVAC Mode
  description: Set the HVAC mode of a climate device.
  target:
    entity:
      integration: virtual
      domain: climate
  fields:
    hvac_mode:
      name: HVAC Mode
      description: HVAC mode to set.
      example: 'heat'
      required: true
      selector:
        select:
          options:
            - 'off'
            - 'heat'
            - 'cool'
            - 'heat_cool'
            - 'dry'
            - 'fan_only'

set_climate_fan_mode:
  name: Set Climate Fan Mode
  description: Set the fan mode of a climate device.
  target:
    entity:
      integration: virtual
      domain: climate
  fields:
    fan_mode:
      name: Fan Mode
      description: Fan mode to set.
      example: 'auto'
      required: true
      selector:
        select:
          options:
            - 'auto'
            - 'low'
            - 'medium'
            - 'high'

move:
  name: Move
  description: Move a device tracker to a new location.
  target:
    entity:
      integration: virtual
      domain: device_tracker
  fields:
    location:
      name: Named Location
      description: Where to move the device tracker to.
      example: 'home'
      selector:
        text:
    gps:
      name: GPS Location
      description: Which coordinates to move the device tracker to.
      example: '{"latitude": -27.9699373, "longitude": 153.4081865}'
      selector:
        location:
          radius: false
    gps_accuracy:
      selector:
        number:
          min: 0
          mode: box
          unit_of_measurement: "m"
