# Describes the format for available virtual services

turn_on:
  description: Turn on a binary sensor.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'binary_sensor.virtual_motion_1'

turn_off:
  description: Turn off a binary sensor.
  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'binary_sensor.virtual_motion_1'

toggle:
  description: Toggle a binary sensor.
  fields:
    entity_id:
      description: Name(s) of entities to toggle
      example: 'binary_sensor.virtual_motion_1'

set:
  description: Set value of a sensor.
  fields:
    entity_id:
      description: Name(s) of entities to toggle
      example: 'sensor.virtual_motion_battery'
    value:
      description: Value to set
      example: 10

set_available:
  description: Set availability of a entity.
  fields:
    entity_id:
      description: Name(s) of entities to set
      example: 'switch.virtual_switch_1'
    value:
      description: Value to set
      example: false

move:
  description: Move a device tracker to a new location
  fields:
    entity_id:
      description: Name(s) of entities to set
      example: 'device_tracker.kasandra'
    location:
      description: Where to move to
      example: 'home'
